name: Deploy no cluster Kubernetes
on:
  workflow_call:
    inputs:
      manifests:
        type: string
        required: true
        description: "imagens serao alteradas nos manifestos"
      images:
        type: string
        required: true
        description: "imagens serao alteradas nos manifestos"
jobs:
  deploy-k8s:
    runs-on: self-hosted
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: ${{ inputs.manifests }}
        images: ${{ inputs.images }}
